name: Paul Perry
description: Paul Perry's site
author: Paul Perry
author_email: pop@paulperry.net
url: http://www.paulperry.net
permalink: pretty
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

gems:
  - jekyll-redirect-from

analytics :
  provider : google
  google : 
      tracking_id : 'UA-21253165-1'
